#### Q1. Write code to create a 4*3 matrix with values ranging from 2 to 13.

In [1]:
import numpy as np

In [4]:
matrix = np.arange(2, 14).reshape(4, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


#### Q3. perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.
a. Create a 1d-array of mobile phones prices.

In [19]:
arr = np.array([6999, 7500, 11999, 27899, 14999, 9999])
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999])

In [20]:
arr.ndim    #just check

1

b. Convert this array to float type.

In [22]:
arr = arr.astype(float)
arr

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

In [23]:
arr.dtype  #check data type

dtype('float64')