#### Q3. perrform the following operations on an array of mobile phones price 6999, 7500, 1199, 27899, 14999, 9999.
a. Create a 1d-array of mobile phones prices.

In [2]:
import numpy as np

arr = np.array([6999, 7500, 1199, 27899, 14999, 9999 ])
arr

array([ 6999,  7500,  1199, 27899, 14999,  9999])

In [5]:
arr.ndim   #check array dimension 

1

b. Convert this array to float type.

In [4]:
arr = arr.astype(float)
arr

array([ 6999.,  7500.,  1199., 27899., 14999.,  9999.])

In [6]:
arr.dtype        #check datatype

dtype('float64')

c. Append a new mobile having price of 13999 Rs. to this array

In [10]:
arr = np.append(arr, 13999)
arr

array([ 6999.,  7500.,  1199., 27899., 14999.,  9999., 13999.])

d. Reverse this array of mobile having price of 13999 Rs. to this array 

In [13]:
arr = np.flip(arr)
arr

array([13999.,  9999., 14999., 27899.,  1199.,  7500.,  6999.])

e. Apply GST of 18% on mobile phones prices and update this array.

In [21]:
arr = np.array([6999, 7500, 11999, 27899, 14999, 9999, 13999])

arr = arr * 1.18
arr

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

f. Sort the array in descending order of price 

In [26]:
np.sort(arr)[::-1]
arr

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

g. What is the average mobile phone price.

In [28]:
arr = np.mean(arr)
arr

np.float64(15743.560000000001)

H. What is the difference b/w maximum and minimum price 

In [30]:
arr = np.max(arr) - np.min(arr)
arr 

np.float64(0.0)